apiVersion: v1
kind: Service
metadata:
  labels:
    name: tsb-operator
    platform.tsb.tetrate.io/application: tsb-operator-managementplane
    platform.tsb.tetrate.io/component: tsb-operator
    platform.tsb.tetrate.io/plane: management
  name: tsb-operator-management-plane
  namespace: 'tsb'
spec:
  ports:
  - name: http-metrics
    port: 8383
    targetPort: 8383
  - name: webhook
    port: 443
    targetPort: 443
  selector:
    name: tsb-operator