apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: elastic-operator
    meta.helm.sh/release-namespace: elastic
  labels:
    app.kubernetes.io/instance: elastic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: elastic
    app.kubernetes.io/version: 1.7.1
    helm.sh/chart: eck-operator-1.7.1
  name: elastic
  namespace: elastic
